### ISSUE TITLE
Demo Repo Errors in Console?

### ISSUE THREAD

**Issue by Diddyy** [laravel-filament/filament#10185]
### Package

filament/tables

### Package Version

Demo Version

### Laravel Version

Demo Version

### PHP Version

Demo PHP Version

### Problem description

I have searched in the repo and cannot find it anywhere.
I have been experiencing an issue with tables where I apply a filter and everything works, but I get warnings and errors fill my browser console log.

Thought I'd check if it happens on the demo and it does.
Upon going to https://demo.filamentphp.com/shop/customers and clicking filters then clicking 'Only Deleted Records' it logs the errors below.

I get it may be due to there being no records to show or it being used before it was ready, just wondering if theres a way to fix the error so it doesn't appear or at least surpress it if there is no fix available?

### Expected behavior

No errors or warnings in console log

### Steps to reproduce

1. Go to https://demo.filamentphp.com/shop/customers
2. Click Filters > 'Only Deleted Records'
3. See error and warnings in console log

### Reproduction repository

https://github.com/filamentphp/demo

### Relevant log output

```shell
livewire.js?id=8afc12b0:1250 Alpine Expression Error: Cannot read properties of undefined (reading 'getElementsByClassName')

Expression: "const recordsOnPage = getRecordsOnPage()

                                            if (recordsOnPage.length && areRecordsSelected(recordsOnPage)) {
                                                $el.checked = true

                                                return 'checked'
                                            }

                                            $el.checked = false

                                            return null"

 <input type=​"checkbox" class=​"fi-checkbox-input rounded border-none bg-white shadow-sm ring-1 transition duration-75 checked:​ring-0 focus:​ring-2 focus:​ring-offset-0 disabled:​pointer-events-none disabled:​bg-gray-50 disabled:​text-gray-50 disabled:​checked:​bg-current disabled:​checked:​text-gray-400 dark:​bg-white/​5 dark:​disabled:​bg-transparent dark:​disabled:​checked:​bg-gray-600 text-primary-600 ring-gray-950/​10 focus:​ring-primary-600 checked:​focus:​ring-primary-500/​50 dark:​text-primary-500 dark:​ring-white/​20 dark:​checked:​bg-primary-500 dark:​focus:​ring-primary-500 dark:​checked:​focus:​ring-primary-400/​50 dark:​disabled:​ring-white/​10" wire:loading.attr=​"disabled" wire:target=​"gotoPage,nextPage,previousPage,removeTableFilter,removeTableFilters,reorderTable,resetTableFiltersForm,sortTable,tableColumnSearches,tableFilters,tableRecordsPerPage,tableSearch" x-bind:checked=​"const recordsOnPage = getRecordsOnPage()​

                                            if (recordsOnPage.length && areRecordsSelected(recordsOnPage)​)​ {
                                                $el.checked = true

                                                return 'checked'
                                            }​

                                            $el.checked = false

                                            return null" x-on:click=​"toggleSelectRecordsOnPage">​
handleError @ livewire.js?id=8afc12b0:1250
(anonymous) @ livewire.js?id=8afc12b0:1323
Promise.catch (async)
(anonymous) @ livewire.js?id=8afc12b0:1323
tryCatch @ livewire.js?id=8afc12b0:1243
(anonymous) @ livewire.js?id=8afc12b0:3484
reactiveEffect @ livewire.js?id=8afc12b0:2408
flushJobs @ livewire.js?id=8afc12b0:780

livewire.js?id=8afc12b0:1254 Uncaught TypeError: Cannot read properties of undefined (reading 'getElementsByClassName')
    at Proxy.getRecordsOnPage (https://demo.filamentphp.com/js/filament/tables/components/table.js?v=3.1.9.0:1:1206)
    at eval (eval at safeAsyncFunction (https://demo.filamentphp.com/livewire/livewire.js?id=8afc12b0:1301:21), <anonymous>:3:66)
    at [Alpine] const recordsOnPage = getRecordsOnPage()

                                            if (recordsOnPage.length && areRecordsSelected(recordsOnPage)) {
                                                $el.checked = true

                                                return 'checked'
                                            }

                                            $el.checked = false

                                            return null (eval at safeAsyncFunction (https://demo.filamentphp.com/livewire/livewire.js?id=8afc12b0:1301:21), <anonymous>:13:59)
    at https://demo.filamentphp.com/livewire/livewire.js?id=8afc12b0:1323:23
    at tryCatch (https://demo.filamentphp.com/livewire/livewire.js?id=8afc12b0:1243:14)
    at https://demo.filamentphp.com/livewire/livewire.js?id=8afc12b0:3484:19
    at Array.reactiveEffect (https://demo.filamentphp.com/livewire/livewire.js?id=8afc12b0:2408:16)
    at flushJobs (https://demo.filamentphp.com/livewire/livewire.js?id=8afc12b0:780:15)
getRecordsOnPage @ table.js?v=3.1.9.0:1
eval @ VM378:3
[Alpine] const recordsOnPage = getRecordsOnPage()

                                            if (recordsOnPage.length && areRecordsSelected(recordsOnPage)) {
                                                $el.checked = true

                                                return 'checked'
                                            }

                                            $el.checked = false

                                            return null @ VM378:13
(anonymous) @ livewire.js?id=8afc12b0:1323
tryCatch @ livewire.js?id=8afc12b0:1243
(anonymous) @ livewire.js?id=8afc12b0:3484
reactiveEffect @ livewire.js?id=8afc12b0:2408
flushJobs @ livewire.js?id=8afc12b0:780
setTimeout (async)
handleError @ livewire.js?id=8afc12b0:1253
(anonymous) @ livewire.js?id=8afc12b0:1323
Promise.catch (async)
(anonymous) @ livewire.js?id=8afc12b0:1323
tryCatch @ livewire.js?id=8afc12b0:1243
(anonymous) @ livewire.js?id=8afc12b0:3484
reactiveEffect @ livewire.js?id=8afc12b0:2408
flushJobs @ livewire.js?id=8afc12b0:780

table.js?v=3.1.9.0:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'getElementsByClassName')
    at Proxy.getRecordsOnPage (https://demo.filamentphp.com/js/filament/tables/components/table.js?v=3.1.9.0:1:1206)
    at eval (eval at safeAsyncFunction (https://demo.filamentphp.com/livewire/livewire.js?id=8afc12b0:1301:21), <anonymous>:3:66)
    at [Alpine] const recordsOnPage = getRecordsOnPage()

                                            if (recordsOnPage.length && areRecordsSelected(recordsOnPage)) {
                                                $el.checked = true

                                                return 'checked'
                                            }

                                            $el.checked = false

                                            return null (eval at safeAsyncFunction (https://demo.filamentphp.com/livewire/livewire.js?id=8afc12b0:1301:21), <anonymous>:13:59)
    at https://demo.filamentphp.com/livewire/livewire.js?id=8afc12b0:1323:23
    at tryCatch (https://demo.filamentphp.com/livewire/livewire.js?id=8afc12b0:1243:14)
    at https://demo.filamentphp.com/livewire/livewire.js?id=8afc12b0:3484:19
    at Array.reactiveEffect (https://demo.filamentphp.com/livewire/livewire.js?id=8afc12b0:2408:16)
    at flushJobs (https://demo.filamentphp.com/livewire/livewire.js?id=8afc12b0:780:15)
getRecordsOnPage @ table.js?v=3.1.9.0:1
eval @ VM378:3
[Alpine] const recordsOnPage = getRecordsOnPage()

                                            if (recordsOnPage.length && areRecordsSelected(recordsOnPage)) {
                                                $el.checked = true

                                                return 'checked'
                                            }

                                            $el.checked = false

                                            return null @ VM378:13
(anonymous) @ livewire.js?id=8afc12b0:1323
tryCatch @ livewire.js?id=8afc12b0:1243
(anonymous) @ livewire.js?id=8afc12b0:3484
reactiveEffect @ livewire.js?id=8afc12b0:2408
flushJobs @ livewire.js?id=8afc12b0:780
Promise.then (async)
runIfTypeOfFunction @ livewire.js?id=8afc12b0:1344
(anonymous) @ livewire.js?id=8afc12b0:1325
tryCatch @ livewire.js?id=8afc12b0:1243
(anonymous) @ livewire.js?id=8afc12b0:3484
reactiveEffect @ livewire.js?id=8afc12b0:2408
flushJobs @ livewire.js?id=8afc12b0:780
```

**Comment by thethunderturner** [comment]
Issue has been resolved!

**Comment by brenjt** [comment]
What was the fix? I am getting this error on a brand new install with this filter.
```
Tables\Filters\SelectFilter::make('roles')
                    ->multiple()
                    ->preload()
                    ->relationship('roles', 'name')
```

**Comment by thethunderturner** [comment]
> What was the fix? I am getting this error on a brand new install with this filter.
> 
> ```
> Tables\Filters\SelectFilter::make('roles')
>                     ->multiple()
>                     ->preload()
>                     ->relationship('roles', 'name')
> ```

It was a livewire bug. I'm not using preload or relationship in my Filter. At least I'm nor getting any errors

**Comment by sitenzo** [comment]
@thethunderturner This problem is still available if you define a custom theme.
For Reproduction repository see : [Custom theme bug](https://github.com/sitenzo/FilamentGlobalSettings/tree/testing-livewire-bug)

If you comment out line 58 *->viteTheme('resources/css/filament/admin/theme.css')* on **AdminPanelProvider** there are no more errors.

**Comment by IgordeOliveira** [comment]
I'm having the same bug and I use a custom theme too, although no seems that this issue affect or break something, visibly at least

**Comment by zepfietje** [comment]
Can't reproduce this issue in the demo.
Feel free to create a new bug report with minimal reproduction repository.

**Comment by thethunderturner** [comment]
> Can't reproduce this issue in the demo. Feel free to create a new bug report with minimal reproduction repository.

Yeah, the issue was fixed about a month ago. It was an alpine bug
