### ISSUE TITLE
spa() mode kills the spark redirects

### ISSUE THREAD

**Issue by StaffCollab** [laravel-filament/filament#10855]
### Package

filament/filament

### Package Version

3.x

### Laravel Version

10

### Livewire Version

v3

### PHP Version

8.3

### Problem description

when spa() mode is enabled on configuration, the spark billing link doesn't work

### Expected behavior

remove the wire:navigate from that link

### Steps to reproduce

add filament multi-tenancy
(my project has a custom billable NOT the user... maybe on the user it works since it doesn't need to redirect)
install filament spark
add spa() mode to config
check if the billing URL works

### Reproduction repository

cannot do it because spark is paid and cannot be poublic

**Comment by StaffCollab** [comment]
Cannot add this URL, since spark should not be placed on a public Git as far as I know

**Comment by Montaserz** [comment]
Same here

**Comment by Montaserz** [comment]
Redirect is fixed in Spark release v4.2.11.

**Comment by StaffCollab** [comment]
No, I use 5.0 and it is still the same...

**Comment by vvdboogaard** [comment]
This also happens with Socialite urls under SPA mode.

```
return Action::make('authenticateButton')
            ->color('info')
            ->icon('heroicon-o-arrow-right-on-rectangle')
            ->url(fn (): string => route('login.google'))
            ->label(__('Login with Google'));
```

Probably because of the `wire:navigate` attribute on the button/links with external links.

**Comment by FrankWiebe** [comment]
I'm running into this issue as well. Has anyone found a solution yet?
I'm using Spark 5.0

**Comment by StaffCollab** [comment]
We should be able to add the spark link to the URL exceptions, but I'm unsure if we can pass dynamic routes. Any thoughts

----

Actually, you can use an *, but it does not solve the issue. no idea why
