### ISSUE TITLE
Form Select in Livewire Component - Alpine error

### ISSUE THREAD

**Issue by sakaye** [laravel-filament/filament#15649]
### Package

filament/filament

### Package Version

v3.2.141

### Laravel Version

v11.43.2

### PHP Version

PHP 8.3.17

### Problem description

When using a Form Select with native(false) within a Livewire Component the select doesn't load and an error is thrown in the console.

Uncaught ReferenceError: selectFormComponent is not defined at [Alpine] selectFormComponent

Using the same Form Select inside a Filament Resource works fine.

In testing with my real project, Filament Version 3.2.137 doesn't produce the bug. However I didn't go through these steps with the fresh project.

### Expected behavior

The Select input should load propertly in a Livewire component.

### Steps to reproduce

Install fresh laravel
Install filament
Create simple Model with migration `php artisan make:model Post -m`
Create Filament Resource with Select form object `php artisan make:filament-resource Post`
Create Livewire componet `php artisan make:livewire CreatePost`

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/sakaye/filament-select-bug

### Relevant log output

```shell
Uncaught ReferenceError: selectFormComponent is not defined
    at [Alpine] selectFormComponent({
                            canSelectPlaceholder: false,
                            isHtmlAllowed: false,
                            getOptionLabelUsing: async () => {
                                return await $wire.getFormSelectOptionLabel('status')
                            },
                            getOptionLabelsUsing: async () => {
                                return await $wire.getFormSelectOptionLabels('status')
                            },
                            getOptionsUsing: async () => {
                                return await $wire.getFormSelectOptions('status')
                            },
                            getSearchResultsUsing: async (search) => {
                                return await $wire.getFormSelectSearchResults('status', search)
                            },
                            isAutofocused: false,
                            isMultiple: false,
                            isSearchable: false,
                            livewireId: 'v4Xj7dLe0EirbTGcERtn',
                            hasDynamicOptions: false,
                            hasDynamicSearchResults: false,
                            loadingMessage: 'Loading...',
                            maxItems: null,
                            maxItemsMessage: 'Only  can be selected.',
                            noSearchResultsMessage: 'No options match your search.',
                            options: JSON.parse('[{\u0022label\u0022:\u0022Draft\u0022,\u0022value\u0022:\u0022Draft\u0022,\u0022disabled\u0022:false},{\u0022label\u0022:\u0022Published\u0022,\u0022value\u0022:\u0022Published\u0022,\u0022disabled\u0022:false},{\u0022label\u0022:\u0022Archived\u0022,\u0022value\u0022:\u0022Archived\u0022,\u0022disabled\u0022:false}]'),
                            optionsLimit: 50,
                            placeholder: 'Select an option',
                            position: null,
                            searchDebounce: 1000,
                            searchingMessage: 'Searching...',
                            searchPrompt: 'Start typing to search...',
                            searchableOptionFields: JSON.parse('[\u0022label\u0022]'),
                            state: $wire.$entangle('status', false),
                            statePath: 'status',
                        }) (eval at safeAsyncFunction (https://filament-select-bug.test/livewire/livewire.js?id=13b7c601:1174:21), <anonymous>:3:16)
    at https://filament-select-bug.test/livewire/livewire.js?id=13b7c601:1196:23
    at tryCatch (https://filament-select-bug.test/livewire/livewire.js?id=13b7c601:1116:14)
    at evaluate (https://filament-select-bug.test/livewire/livewire.js?id=13b7c601:1140:34)
    at Function.<anonymous> (https://filament-select-bug.test/livewire/livewire.js?id=13b7c601:3564:17)
    at flushHandlers (https://filament-select-bug.test/livewire/livewire.js?id=13b7c601:1281:48)
    at stopDeferring (https://filament-select-bug.test/livewire/livewire.js?id=13b7c601:1286:7)
    at deferHandlingDirectives (https://filament-select-bug.test/livewire/livewire.js?id=13b7c601:1289:5)
    at initTree (https://filament-select-bug.test/livewire/livewire.js?id=13b7c601:1479:5)
    at https://filament-select-bug.test/livewire/livewire.js?id=13b7c601:1428:7
```

**Comment by danharrin** [comment]
I've identified this change happens because the `@filamentScripts` are in the `<head>` of your layout instead of in the `<body>`, which I did not test when I made a change. I would strongly suggest moving to the `<body>` for reliability elsewhere, but I have also fixed the root cause in #15651.

**Comment by danprudky** [comment]
I'm using lower versions of laravel on my project and even though I'm updating the filament to 3.2.142, which should be the version with the fix, the problem persists. @danharrin any ideas what else could be the problem? I'm updating the filament from 3.2.134.

PHP 8.3.16, Laravel 10.48.28

**Comment by danharrin** [comment]
Make sure your Filament assets are up to date (`php artisan filament:upgrade`) and not cached. Especially `support.js`.

**Comment by deniscsz** [comment]
I faced the same issue. I upgraded to v3.3.0, then I ran `php artisan filament:upgrade` + clear cache. It resolved to me.

**Comment by BouchantoufZakaria** [comment]
> I faced the same issue. I upgraded to v3.3.0, then I ran `php artisan filament:upgrade` + clear cache. It resolved to me.

thanks , that's solve the problem for me too .. !

**Comment by mohapinkepane** [comment]
For anyone who is still suffering from this issue after trying the above solutions.Here is what solved the issue for me - after two days of suffering - **Clear the browser cache/site cache**. I hope it helps.
