### ISSUE TITLE
[object Object] display on simple repeater

### ISSUE THREAD

**Issue by valpuia** [laravel-filament/filament#8874]
### Package

filament/filament

### Package Version

3.0.67

### Laravel Version

10.26.2

### Livewire Version

3.0.5

### PHP Version

8.2

### Problem description

While using below code, it shows [object Object] in input field when creating
```php
Repeater::make('invitations')
    ->simple(
        TextInput::make('email')
            ->email()
            ->required(),
    )
```
![Screenshot from 2023-10-03 16-54-56](https://github.com/filamentphp/filament/assets/28250303/fdc5f9d3-5727-4a10-a4d6-5e53bb5d795a)

Try to fix here https://github.com/filamentphp/filament/pull/8845 but cannot figure out the problem

### Expected behavior

Empty input field

### Steps to reproduce

Clone, install
Go to User, create new user and check Invitations repeater

### Reproduction repository

https://github.com/valpuia/simple-repeater

**Comment by ilpav12** [comment]
@valpuia if the result in the database that you are looking for is an array of emails you can simply change the `TexInput` name to 'invitations.email':
```php
Repeater::make('invitations')
    ->simple(
        TextInput::make('invitations.email')
            ->email()
            ->required(),
    )
```

**Comment by valpuia** [comment]
> @valpuia if the result in the database that you are looking for is an array of emails you can simply change the `TexInput` name to 'invitations.email':
> 

Yes this does the trick, thanks for head ups

**Comment by ilpav12** [comment]
> > @valpuia if the result in the database that you are looking for is an array of emails you can simply change the `TexInput` name to 'invitations.email':
> 
> Yes this does the trick, thanks for head ups

Perfect! Please close the issue as completed.

**Comment by valpuia** [comment]
No it's not completed, unless the docs teach us like yours then we still want to see the empty input when declaring like docs

**Comment by ilpav12** [comment]
You are correct that was not the right answer because it is empty on edit. It looks like that the is a difference between the value of the first TextInput and the others added manually:
```php
"invitations" => array:2 [
    "cc35096d-4cfc-4207-bbc5-05b70db95fee" => array:1 [
      "email" => array:1 [
        "email" => null
      ]
    ]
    "e44bad27-018c-4ef2-af1e-2edd2947687b" => array:1 [
      "email" => null
    ]
  ]
```
This is why on the first he input shows '[object Object]'.

**Comment by ilpav12** [comment]
This difference is generate by the Repeater class on lines 101 and 105:
```php
foreach ($state ?? [] as $itemData) {
    $items[(string) Str::uuid()] = $simpleField ?
        [$simpleField->getName() => $itemData] :
        $itemData;
}
```
The same loop is present betwen lines 543 and 548.
This generates the extra level that results in '[object Object]'.
When inside the loop I simply put `$items[(string) Str::uuid()] = $itemData;` it works correctly.
@zepfietje please let me know in what cases that code is necessary so I can make a PR.

**Comment by valpuia** [comment]
> because it is empty on edit.

If you don't have any data then always empty on edit (this is normal for simple and main repeater)



> When inside the loop I simply put `$items[(string) Str::uuid()] = $itemData;` it works correctly.

This one create problem in edit (if you have data)

Check this commit https://github.com/filamentphp/filament/pull/8845/commits/6258e82b97eda8e5f4a9e12f0948651bb4383a91, I revert back because of the above problem

**Comment by jdion84** [comment]
i can confirm this is caused by `defaultItems`

when setting `defaultItems(0)`, the new values do not show up as `[object Object]`

to fix this, i modified both occurences of this in the `Repeater` class:

```php
            foreach ($state ?? [] as $itemData) {
                $items[(string) Str::uuid()] = $simpleField ?
                    [$simpleField->getName() => $itemData] :
                    $itemData;
            }
```

with this:

```php
            foreach ($state ?? [] as $itemData) {
                $items[(string) Str::uuid()] = $itemData;
            }
```

however i am unsure if this will break something else, as i havent done any extensive testing on this yet

@danharrin  do you think making this simple fix will break something else?

**Comment by ilpav12** [comment]
@jdion84 as previously stated by @valpuia, this change will show empty fields on edit

**Comment by jdion84** [comment]
i think i found a temporary workaround

add this to your simple repeater:

```
->default([''])
```

**Comment by tuyenhv007** [comment]
Do you have used translation in Model?

**Comment by JUEChristopher** [comment]
> i think i found a temporary workaround
> 
> add this to your simple repeater:
> 
> ```
> ->default([''])
> ```


Not when your field is required, because this default() allow the user to skip it and it go throught the validation like that ...

**Comment by danharrin** [comment]
Fixed by #10046.

**Comment by bartlomiej-przymus** [comment]
@danharrin Thank you for the fix. You beat me to it! And it looks like your fix is working well on my test repo.

While I was working on this component I have noticed that `default()` method on Repeater runs twice even though `$this->defaultItems(1);` is set to one.
I have noticed following two lines after debugging stack trace log that seem to be responsible for this behaviour:
https://github.com/filamentphp/filament/blob/5b3fc20c7cea7b00bf924dc9b2455c4fca71c30a/packages/forms/src/Components/Concerns/HasState.php#L232-L234

Even though this does not seem to affect current functionality I think it might be a typo. Could you enlighten me on this?

**Comment by danharrin** [comment]
Typo! Please submit a PR

**Comment by CharlieEtienne** [comment]
For those still having this issue in 2025, maybe you're using the `getRawState()` method.

When using `getRawState` instead of `getState`, a simple repeater won't be dehydrated as a flat array.

```php
dump($this->form->getState());

// "simple_repeater" => array:3 [▼
//   "value 1"
//   "value 2"
//   "value 3"
// ]

dump($this->form->getRawState());

// "simple_repeater" => array:3 [▼
//   "63428905-c156-44c5-bd1c-7e8e1a056be3" => array:1 [▶]
//   "62127a27-7f86-4edb-bf38-6e78e7aeb2ff" => array:1 [▶]
//   "ef944ed7-3b15-468a-8bd0-4bce0752dc2d" => array:1 [▶]
// ]
```
